repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: golangci-lint-mod
        args: [--fix]
      - id: go-test-mod

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        files: '^web'
        types: []
        types_or: [javascript, vue]
        args:
          - --config=web/eslint.config.js
          - --fix

  - repo: local
    hooks:
      - id: usage-docs
        name: usage-docs
        entry: go run ./internal/cmd/docs
        language: system
        types: [go]
        pass_filenames: false
      - id: config-example
        name: config-example
        entry: go run ./internal/config/generate_example
        language: system
        types: [go]
        pass_filenames: false
