# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  icons: .taskfiles/icons.yaml
  linux: .taskfiles/linux.yaml
  nointro: .taskfiles/nointro.yaml
  palette: .taskfiles/palette.yaml
  web: .taskfiles/web.yaml

tasks:
  build:
    cmds:
      - cmd: ./hack/build-macos.sh
        platforms: [darwin]
      - cmd: go build -ldflags='-w -s' -trimpath -o dist/gones
        platforms: [linux]
      - cmd: ./hack/build-windows.sh
        platforms: [windows]
