// Code generated by "stringer -type Mirror"; DO NOT EDIT.

package cartridge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Horizontal-0]
	_ = x[Vertical-1]
	_ = x[FourScreen-3]
}

const (
	_Mirror_name_0 = "HorizontalVertical"
	_Mirror_name_1 = "FourScreen"
)

var (
	_Mirror_index_0 = [...]uint8{0, 10, 18}
)

func (i Mirror) String() string {
	switch {
	case i <= 1:
		return _Mirror_name_0[_Mirror_index_0[i]:_Mirror_index_0[i+1]]
	case i == 3:
		return _Mirror_name_1
	default:
		return "Mirror(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
