// Code generated by "stringer -type Button -linecomment"; DO NOT EDIT.

package button

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[B-1]
	_ = x[Select-2]
	_ = x[Start-3]
	_ = x[Up-4]
	_ = x[Down-5]
	_ = x[Left-6]
	_ = x[Right-7]
}

const _Button_name = "abselectstartupdownleftright"

var _Button_index = [...]uint8{0, 1, 2, 8, 13, 15, 19, 23, 28}

func (i Button) String() string {
	if i >= Button(len(_Button_index)-1) {
		return "Button(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
