name: Update NoIntro Database

on:
  workflow_dispatch: {}
  schedule:
    - cron: "44 4 1 */3 *"

jobs:
  update-nointro-database:
    name: Update NoIntro Database
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ":arrow_up: Update NoIntro database"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Change Cache Key
        run: echo '// ${{ github.job }}' >> go.sum
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - name: Download database
        run: go generate ./internal/database/...
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          add-paths: "*.csv"
          commit-message: ${{ env.COMMIT_MESSAGE }}
          branch: update-nointro-database
          title: ${{ env.COMMIT_MESSAGE }}
          body: |
            This PR updates the NoIntro database.

            Generated by the Update NoIntro Database Action.
            View update log [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          labels: dependencies,nointro
      - uses: peter-evans/enable-pull-request-automerge@v2
        if: steps.pr.outputs.pull-request-operation == 'created'
        with:
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          merge-method: squash
